#!/usr/bin/env python3
"""Generate `disk.img`: the FAT16 volume rust-os mounts as its filesystem.

The image is gitignored; run this script (`python tools/mkfatimg.py`) once
after cloning, and again after changing the file contents below. `cargo run`
and `cargo test` both attach the image and will fail without it.

Geometry is chosen to be a *spec-conformant* FAT16: the FAT type is defined by
cluster count, and 4085..=65524 clusters means FAT16. At 512-byte clusters the
smallest legal FAT16 is a bit over 2 MiB, which is what this builds.
"""

from __future__ import annotations

import pathlib
import struct

BYTES_PER_SECTOR = 512
SECTORS_PER_CLUSTER = 1
RESERVED_SECTORS = 1
NUM_FATS = 2
ROOT_ENTRIES = 512
TOTAL_SECTORS = 4608  # 2.25 MiB
SECTORS_PER_FAT = 18
MEDIA_DESCRIPTOR = 0xF8
VOLUME_LABEL = b"RUSTOS     "  # exactly 11 bytes
VOLUME_ID = 0x52555354

ROOT_SECTORS = ROOT_ENTRIES * 32 // BYTES_PER_SECTOR
FAT_START = RESERVED_SECTORS
ROOT_START = RESERVED_SECTORS + NUM_FATS * SECTORS_PER_FAT
DATA_START = ROOT_START + ROOT_SECTORS
CLUSTER_COUNT = (TOTAL_SECTORS - DATA_START) // SECTORS_PER_CLUSTER
CLUSTER_BYTES = SECTORS_PER_CLUSTER * BYTES_PER_SECTOR

ATTR_VOLUME = 0x08
ATTR_DIRECTORY = 0x10
ATTR_ARCHIVE = 0x20

# 2024-01-01 in FAT date encoding: ((year - 1980) << 9) | (month << 5) | day
FAT_DATE = ((2024 - 1980) << 9) | (1 << 5) | 1

assert 4085 <= CLUSTER_COUNT <= 65524, f"{CLUSTER_COUNT} clusters is not FAT16"
assert (CLUSTER_COUNT + 2) * 2 <= SECTORS_PER_FAT * BYTES_PER_SECTOR, "FAT too small"

image = bytearray(TOTAL_SECTORS * BYTES_PER_SECTOR)
fat = [0] * (CLUSTER_COUNT + 2)
fat[0] = 0xFF00 | MEDIA_DESCRIPTOR
fat[1] = 0xFFFF
next_free = 2


def cluster_offset(cluster: int) -> int:
    return (DATA_START + (cluster - 2) * SECTORS_PER_CLUSTER) * BYTES_PER_SECTOR


def alloc_chain(data: bytes) -> int:
    """Write `data` into a fresh cluster chain; return its first cluster."""
    global next_free
    if not data:
        return 0
    count = (len(data) + CLUSTER_BYTES - 1) // CLUSTER_BYTES
    first = next_free
    for i in range(count):
        cluster = first + i
        fat[cluster] = 0xFFFF if i == count - 1 else cluster + 1
        chunk = data[i * CLUSTER_BYTES : (i + 1) * CLUSTER_BYTES]
        offset = cluster_offset(cluster)
        image[offset : offset + len(chunk)] = chunk
    next_free += count
    return first


def reserve_cluster() -> int:
    """Reserve one cluster (used for directories, whose number must be known
    before their contents can be built)."""
    global next_free
    cluster = next_free
    next_free += 1
    fat[cluster] = 0xFFFF
    return cluster


def short_name(name: str) -> bytes:
    if name in (".", ".."):
        return name.ljust(11).encode("ascii")
    base, _, ext = name.partition(".")
    assert len(base) <= 8 and len(ext) <= 3, f"{name} is not a valid 8.3 name"
    return (base.ljust(8) + ext.ljust(3)).upper().encode("ascii")


def dir_entry(name: str, attr: int, cluster: int, size: int) -> bytes:
    entry = bytearray(32)
    entry[0:11] = short_name(name)
    entry[11] = attr
    struct.pack_into("<H", entry, 16, FAT_DATE)  # create date
    struct.pack_into("<H", entry, 18, FAT_DATE)  # access date
    struct.pack_into("<H", entry, 20, 0)  # cluster high (always 0 on FAT16)
    struct.pack_into("<H", entry, 24, FAT_DATE)  # write date
    struct.pack_into("<H", entry, 26, cluster)
    struct.pack_into("<I", entry, 28, size)
    return bytes(entry)


def make_file(name: str, text: str) -> bytes:
    data = text.encode("ascii")
    return dir_entry(name, ATTR_ARCHIVE, alloc_chain(data), len(data))


def make_subdir(name: str, files: dict[str, str], parent_cluster: int = 0) -> bytes:
    cluster = reserve_cluster()
    body = bytearray()
    body += dir_entry(".", ATTR_DIRECTORY, cluster, 0)
    body += dir_entry("..", ATTR_DIRECTORY, parent_cluster, 0)
    for filename, text in files.items():
        body += make_file(filename, text)
    assert len(body) <= CLUSTER_BYTES, f"{name}/ needs more than one cluster"
    offset = cluster_offset(cluster)
    image[offset : offset + len(body)] = body
    return dir_entry(name, ATTR_DIRECTORY, cluster, 0)


# ---------------------------------------------------------------- contents --

HELLO = "Hello from the FAT16 filesystem!\n"

README = """\
rust-os disk
============

This volume is a plain FAT16 filesystem, read by the kernel's own ATA PIO
driver and FAT parser -- no firmware, no libraries.

  ls            list the root directory
  ls /docs      list a subdirectory
  cat readme.txt   print a file

Generated by tools/mkfatimg.py.
"""

# 40 lines x 48 bytes = 1920 bytes, so this file spans several clusters and
# exercises FAT chain walking. tests/filesystem.rs asserts on the exact size.
POEM = "".join(
    f"{i:03}: the quick brown fox jumps over the lazy dog\n" for i in range(1, 41)
)

NOTES = """\
Notes
-----
Files in a subdirectory prove path resolution walks the directory tree
rather than only reading the fixed-size FAT16 root region.
"""

ATA_NOTES = """\
ATA PIO, in short
-----------------
Select drive, write the LBA and a sector count, issue command 0x20, poll the
status port until DRQ, then read 256 16-bit words from the data port.
"""

root = bytearray()
root += dir_entry(VOLUME_LABEL.decode("ascii").strip(), ATTR_VOLUME, 0, 0)
root += make_file("HELLO.TXT", HELLO)
root += make_file("README.TXT", README)
root += make_file("POEM.TXT", POEM)
root += make_subdir("DOCS", {"NOTES.TXT": NOTES, "ATA.TXT": ATA_NOTES})
assert len(root) <= ROOT_SECTORS * BYTES_PER_SECTOR, "root directory overflow"

# ------------------------------------------------------------- boot sector --

boot = bytearray(BYTES_PER_SECTOR)
boot[0:3] = b"\xeb\x3c\x90"  # jmp short +0x3c; nop
boot[3:11] = b"MSWIN4.1"
struct.pack_into("<H", boot, 11, BYTES_PER_SECTOR)
boot[13] = SECTORS_PER_CLUSTER
struct.pack_into("<H", boot, 14, RESERVED_SECTORS)
boot[16] = NUM_FATS
struct.pack_into("<H", boot, 17, ROOT_ENTRIES)
struct.pack_into("<H", boot, 19, TOTAL_SECTORS)
boot[21] = MEDIA_DESCRIPTOR
struct.pack_into("<H", boot, 22, SECTORS_PER_FAT)
struct.pack_into("<H", boot, 24, 32)  # sectors per track (unused, CHS legacy)
struct.pack_into("<H", boot, 26, 8)  # heads (likewise)
struct.pack_into("<I", boot, 28, 0)  # hidden sectors
struct.pack_into("<I", boot, 32, 0)  # total sectors (32-bit form, unused)
boot[36] = 0x80  # BIOS drive number
boot[38] = 0x29  # extended boot signature
struct.pack_into("<I", boot, 39, VOLUME_ID)
boot[43:54] = VOLUME_LABEL
boot[54:62] = b"FAT16   "  # the kernel checks this before trusting the BPB
boot[510] = 0x55
boot[511] = 0xAA

# ------------------------------------------------------------------ assemble --

image[0:BYTES_PER_SECTOR] = boot

fat_bytes = bytearray()
for entry in fat:
    fat_bytes += struct.pack("<H", entry)
fat_bytes += bytes(SECTORS_PER_FAT * BYTES_PER_SECTOR - len(fat_bytes))
for copy in range(NUM_FATS):
    offset = (FAT_START + copy * SECTORS_PER_FAT) * BYTES_PER_SECTOR
    image[offset : offset + len(fat_bytes)] = fat_bytes

offset = ROOT_START * BYTES_PER_SECTOR
image[offset : offset + len(root)] = root

out = pathlib.Path(__file__).resolve().parent.parent / "disk.img"
out.write_bytes(image)

print(f"wrote {out} ({len(image)} bytes)")
print(f"  FAT16, {CLUSTER_COUNT} clusters of {CLUSTER_BYTES} bytes")
print(f"  fat@{FAT_START} root@{ROOT_START} data@{DATA_START}")
print(f"  {next_free - 2} clusters used")
